-- Use an admin role
USE ROLE ACCOUNTADMIN;

-- Create the 'transform' role
DROP ROLE IF EXISTS TRANSFORM;
CREATE ROLE TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create the 'dbt' user and assign to role
DROP USER IF EXISTS dbt;
CREATE USER IF NOT EXISTS dbt
    LOGIN_NAME='dbt'
    TYPE=SERVICE
    RSA_PUBLIC_KEY='
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrcnrLBKNP6w24ySde4h
B1hiHo/Z+FiumU+ohJk4BZUZn0jk3wiocSqrxhYpUs3ciYA9hCQJ77W5LN02j+08
djeo15vclqV8GMU4mSl5zC8lAsiFXhvt+Zd6bMTBWeQqjGaAgqGnbmBmkjwsWfqB
MAqRDxF5DoqDy0hG4ruzXgixHba4Dzm8SasNtgooqaIj+ol66Vh8RZfaAjEXj+2m
rkFRuwj1pNJgeEwGx10FJzCR9y2JE8kYaBi3ogucUC1YdjqjcjHqGUjyXlyID1Fq
bBeB7Fg1h111UnxL97qVe2Y0PgzROCv6ATbOHFberJnemKOsHVgJn5Q0NBTeif/L
ewIDAQAB
'
    DEFAULT_ROLE=TRANSFORM
    DEFAULT_WAREHOUSE='COMPUTE_WH'
    DEFAULT_NAMESPACE='AIRBNB.RAW'
    COMMENT='DBT user used for data transformation';

GRANT ROLE TRANSFORM TO USER dbt;

-- Set up permissions to role 'transform'
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE AIRBNB TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE AIRBNB TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE AIRBNB TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA AIRBNB.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA AIRBNB.RAW TO ROLE TRANSFORM;

-- Create the user and permissions for Preset.io
USE ROLE ACCOUNTADMIN;

DROP ROLE IF EXISTS REPORTER;
CREATE ROLE REPORTER;

DROP USER IF EXISTS PRESET;
CREATE USER PRESET
    LOGIN_NAME='preset'
    TYPE=SERVICE
    RSA_PUBLIC_KEY='
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrcnrLBKNP6w24ySde4h
B1hiHo/Z+FiumU+ohJk4BZUZn0jk3wiocSqrxhYpUs3ciYA9hCQJ77W5LN02j+08
djeo15vclqV8GMU4mSl5zC8lAsiFXhvt+Zd6bMTBWeQqjGaAgqGnbmBmkjwsWfqB
MAqRDxF5DoqDy0hG4ruzXgixHba4Dzm8SasNtgooqaIj+ol66Vh8RZfaAjEXj+2m
rkFRuwj1pNJgeEwGx10FJzCR9y2JE8kYaBi3ogucUC1YdjqjcjHqGUjyXlyID1Fq
bBeB7Fg1h111UnxL97qVe2Y0PgzROCv6ATbOHFberJnemKOsHVgJn5Q0NBTeif/L
ewIDAQAB
'
    DEFAULT_WAREHOUSE='COMPUTE_WH'
    DEFAULT_ROLE=REPORTER
    DEFAULT_NAMESPACE='AIRBNB.DEV'
    COMMENT='Preset user for creating reports';

GRANT ROLE REPORTER TO USER PRESET;
GRANT ROLE REPORTER TO ROLE ACCOUNTADMIN;
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE REPORTER;
GRANT USAGE ON DATABASE AIRBNB TO ROLE REPORTER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AIRBNB TO ROLE REPORTER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AIRBNB TO ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN SCHEMA AIRBNB.DEV TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AIRBNB.DEV TO ROLE REPORTER;
    
